CREATE DATABASE CONSULTORIA_GLOBAL

CREATE TABLE DEPARTAMENTO (
    NID_DEP      NUMBER          NOT NULL
   ,VNOME_DEP    VARCHAR2(50)    NOT NULL
   ,VLOCAL_DEP   VARCHAR2(50)    NOT NULL

   ,CONSTRAINT   PK_DEP PRIMARY KEY (NID_DEP)
)

CREATE TABLE GESTAO (
    NID_GEST           NUMBER         NOT NULL
   ,VNOME_GEST         VARCHAR2(100)  NOT NULL
   ,VAREAATUA_GEST VARCHAR2(50)   NOT NULL
   ,NID_DEP            NUMBER         NOT NULL

   ,CONSTRAINT   PK_GESTAO PRIMARY       KEY (NID_GEST)
   ,CONSTRAINT   FK_DEPARTAMENTO FOREIGN KEY (NID_DEP)    REFERENCES DEPARTAMENTO (DEP_ID)
)


CREATE TABLE PROJETO (
    NID_PROJ        NUMBER          NOT NULL
   ,VTITULO_PROJ    VARCHAR2(100)   NOT NULL
   ,NORCAMENTO_PROJ NUMBER(12,2)    NOT NULL
   ,CSTATUS_PROJ    CHAR(1)         NOT NULL --(Ex: 'A-ATIVO', 'C-CONCLUIDO', 'P-PENDENTE')

   ,CONSTRAINT   PK_PROJ PRIMARY KEY (NID_PROJ)
)

CREATE TABLE ALOCACAO (
    NID_ALOC        NUMBER          NOT NULL
   ,NID_GEST        NUMBER          NOT NULL
   ,NID_PROJ        NUMBER          NOT NULL
   ,NHORA_ALOC      NUMBER(5)       NOT NULL
   ,DDATINI_ALOC    DATE            NOT NULL
   ,DDATFIN_ALOC    DATE

   ,CONSTRAINT   PK_ALOC    PRIMARY KEY (NID_ALOC)
   ,CONSTRAINT   FK_GESTAO  FOREIGN KEY (NID_GEST) REFERENCES GESTAO  (NID_GEST)
   ,CONSTRAINT   FK_PROJETO FOREIGN KEY (NID_PROJ) REFERENCES PROJETO (NID_PROJ)
)